### ISSUE TITLE
[Angular] npm test fails

### ISSUE THREAD

**Issue by godanny86** [adobe/aem-guides-wknd-spa#9]
Error occurs when npm test is run:

```
ERROR in src/app/components/page/page.component.spec.ts:42:49 - error TS2345: Argument of type '() => Promise<{}>' is not assignable to parameter of type '<M extends Model>(config?: string | ModelManagerConfiguration) => Promise<M>'.
  Type 'Promise<{}>' is not assignable to type 'Promise<M>'.
    Type '{}' is not assignable to type 'M'.
      '{}' is assignable to the constraint of type 'M', but 'M' could be instantiated with a different subtype of constraint 'Model'.
```

**Comment by viveksr2** [comment]
Facing the same issue while creating Archetype 23 project on Linux server. On Windows it is working fine.
![error](https://user-images.githubusercontent.com/5589773/91166883-ad2a6e00-e6f0-11ea-9d9f-3b64a7abef0b.png)

**Comment by viveksr2** [comment]
Any updates on this issue?

**Comment by godanny86** [comment]
@viveksr2 engineering is still looking in to it. In the mean time you can simply remove the file: `src/app/components/page/page.component.spec.ts` to get around it...

**Comment by godanny86** [comment]
Actually this has been fixed in the archetype and this project will be updated today. @viveksr2 checkout the changes here: https://github.com/adobe/aem-project-archetype/pull/461/files

**Comment by godanny86** [comment]
This has been fixed across Angular branches: https://github.com/adobe/aem-guides-wknd-spa/commit/ec0e25654153e60d6229b5a5af0418132935acfb

**Comment by viveksr2** [comment]
Thanks for the information @godanny86 👍
